### ISSUE TITLE
The demo config seems not working

### ISSUE THREAD

**Issue by 18601673727** [Glorian/laravel-elixir-webpack-advanced#1]
Config:

``` javascript
elixir(function(mix) {
    mix.webpack(
        { bundle: 'app.js', vendor: ['jquery'] }, 
        {
            outputDir: "public/js",
            output: {
                filename: "bundle.js"
            }
        }, 
        {
            $: 'jquery',
            jQuery: 'jquery',
            'window.jQuery': 'jquery'
        }
    );
});
```

Run:

```
gulp
```

Error:

```
path.js:9
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received [ 'jquery' ]
    at assertPath (path.js:9:11)
    at Object.posix.join (path.js:480:5)
    at prefixOne (/opt/code/node_modules/laravel-elixir/GulpPaths.js:108:22)
    at Array.map (native)
    at GulpPaths.prefix (/opt/code/node_modules/laravel-elixir/GulpPaths.js:117:21)
    at GulpPaths.src (/opt/code/node_modules/laravel-elixir/GulpPaths.js:20:16)
    at module.exports (/opt/code/node_modules/laravel-elixir-webpack-advanced/lib/GulpPaths.js:23:10)
    at Function.<anonymous> (/opt/code/node_modules/laravel-elixir-webpack-advanced/index.js:25:17)
    at Function.<anonymous> (/opt/code/node_modules/laravel-elixir/index.js:40:18)
    at /opt/code/gulpfile.js:29:7
```

**Comment by Glorian** [comment]
Corrected :)
