### ISSUE TITLE
Clean installation not working, `ReferenceError: Elixir is not defined.`

### ISSUE THREAD

**Issue by Caroga** [Glorian/laravel-elixir-webpack-advanced#10]
Hi,
I found your npm package and have tried using it but it generates a ReferenceError upon running.

```
$ ./node_modules/.bin/gulp
C:\wamp64\www\lokaal.mijn.appelsap.nl\node_modules\laravel-elixir-webpack-advanced\dist\modules\IsVersioning.js:15
return Elixir.inProduction && (0, _lodash.get)(Elixir.config, 'versioning.enabled', false);
^

ReferenceError: Elixir is not defined
at exports.default (C:\wamp64\www\lokaal.mijn.appelsap.nl\node_modules\laravel-elixir-webpack-advanced\dist\modules\IsVersioning.js:15:10)
at Object.<anonymous> (C:\wamp64\www\lokaal.mijn.appelsap.nl\node_modules\laravel-elixir-webpack-advanced\dist\Config.js:59:50)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\wamp64\www\lokaal.mijn.appelsap.nl\node_modules\laravel-elixir-webpack-advanced\dist\index.js:33:15)
```

This is the package.json file contents:

```
{
    "private": true,
    "dependencies": {
        "bootstrap-sass": "^3.0.0",
        "gulp": "^3.8.8",
        "jquery-file-download": "^1.4.5",
        "laravel-elixir": "^4.0.0",
        "laravel-elixir-webpack-advanced": "^0.3.9-3"
    }
}
```

This is my Gulpfile.js content:

```
var elixir = require('laravel-elixir');

require("laravel-elixir-webpack-advanced");

var javascriptFiles = [
    'fileDownloader.js',
    'fileUploader.js'
];

elixir(function (mix) {
    mix.webpack(javascriptFiles);
});
```

As you can see, there is nothing special going on in there.
I did noticed that inside `laravel-elixir-webpack-advanced/dist/modules/IsVersioning.js` elixir is referenced by with a capital E. I don't know if this would cause the problem or something else I may have misconfigured.

Could you maybe take a look into this ?
Thanks in advance.

**Comment by Glorian** [comment]
Can you tell me your version of laravel-elixir?
I gues you need update laravel-elixir dependency to ~v6.0.0-10 or higher

**Comment by Caroga** [comment]
Hi Glorian,

Turns out I was using 4.x instead of 6.x, and this indeed was causing the problem. 
I will close this issue. 
Thank you for your fast response!

Kind regards
