### ISSUE TITLE
How can i Use this in a New Laravel Fresh Install App?

### ISSUE THREAD

**Issue by masterpowers** [Glorian/laravel-elixir-webpack-advanced#2]
Ive tried to install 
but im getting this error
Any reason for this?

```
Error: Cannot find module 'laravel-elixir-webpack-advanced'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/vagrant/codes/royalflushnetwork.dev/gulpfile.js:8:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by Glorian** [comment]
Can you show me your `gulpfile.js`?

**Comment by Glorian** [comment]
@masterpowers, I think you didn't install appropriate packages for executing gulp task.
First of all you should do this:

``` bash
# This command will install everything that we need and write devDependencies in package.json
npm i -D gulp laravel-elixir laravel-elixir-webpack-advanced 
```
