### ISSUE TITLE
elixir.isWatching is not a function ?

### ISSUE THREAD

**Issue by mehrancodes** [Glorian/laravel-elixir-webpack-advanced#8]
Got this error even on a fresh Laravel install.
Using node.js 4 and 6.

When runinning `gulp`:

``` bash
/node_modules/laravel-elixir-webpack-advanced/conf/webpack.js:197
if (!elixir.isWatching()) {
            ^

TypeError: elixir.isWatching is not a function
    at Object.<anonymous> (/home/mehran/code/webpack/node_modules/laravel-elixir-webpack-advanced/conf/webpack.js:197:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/mehran/code/webpack/node_modules/laravel-elixir-webpack-advanced/index.js:11:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by IhorKevin** [comment]
+1

**Comment by Glorian** [comment]
@miranrasuli, type in terminal `npm list --depth=0` under your project root and write here **laravel-elixir** version.
There is a suspicion that the version of laravel-elixir less then 6.0*

**Comment by mehrancodes** [comment]
@Glorian Sorry for the delay!

It is the result of `npm list --depth=0`

``` bash
├── gulp@3.9.1
├── laravel-elixir@5.0.0
├── laravel-elixir-webpack-advanced@0.3.8
├── stylus@0.54.5
└── stylus-loader@2.1.1
```

laravel elixir was v6. but even after changing that to v5, it still throws that error

**Comment by Glorian** [comment]
@miranrasuli, I'll fix this today.
